# Generated by Django 3.2.4 on 2021-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='edit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='fin',
            field=models.BooleanField(null=True),
        ),
    ]
