# Generated by Django 3.2.4 on 2021-06-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210616_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='fin',
        ),
    ]
